"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ClockIcon, ChevronDownIcon, Loader2Icon } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { createProblem } from "@/actions/create-problem";
import { ClientFacingUserObject } from "@/lib/auth-types";
import { FocusAreaSelector } from "@/components/focus-area-selector";
import type { FocusArea } from "@repo/api-types";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";

interface NewProblemViewProps {
  user: ClientFacingUserObject | null;
  focusAreas: FocusArea[];
}

export default function NewProblemView({
  user,
  focusAreas,
}: NewProblemViewProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [focusAreasOpen, setFocusAreasOpen] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Initialize selected focus areas from URL params if present
  const [selectedFocusAreaIds, setSelectedFocusAreaIds] = useState<string[]>(
    () => {
      if (typeof window === "undefined") return [];
      const params = new URLSearchParams(window.location.search);
      const focusAreasParam = params.get("focusAreas");
      if (focusAreasParam) {
        const ids = focusAreasParam.split(",").filter(Boolean);
        return ids.filter((id) => focusAreas.some((area) => area.id === id));
      }
      return [];
    },
  );

  // Auto-generate if flag is set and user is logged in
  useEffect(() => {
    const shouldAutoGenerate = searchParams.get("autoGenerate") === "true";
    if (shouldAutoGenerate && user && !isGenerating && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      handleGenerateProblem();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user, searchParams]);

  const handleGenerateProblem = async () => {
    // If user is not logged in, redirect to login with focus areas in state
    if (!user) {
      const focusAreasParam =
        selectedFocusAreaIds.length > 0
          ? `?focusAreas=${selectedFocusAreaIds.join(",")}`
          : "";
      router.push(`/login${focusAreasParam}`);
      return;
    }

    setIsGenerating(true);
    try {
      // Use first available model (backend will use default)
      const result = await createProblem(
        "claude-sonnet-4-20250514", // Default model
        user.apiKey,
        true, // autoGenerate
        undefined, // returnDummy
        undefined, // startFrom
        selectedFocusAreaIds.length > 0 ? selectedFocusAreaIds : undefined,
      );
      router.push(`/problem/${result.problemId}`);
    } catch (error) {
      console.error("Failed to create problem:", error);
      setIsGenerating(false);
    }
  };

  return (
    <div className="h-full overflow-auto p-4 flex flex-col gap-6 bg-card">
      {/* Status Indicator */}
      <div className="border border-border rounded-lg p-3 bg-accent space-y-2">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            {isGenerating ? (
              <Loader2Icon className="h-4 w-4 animate-spin text-primary" />
            ) : (
              <ClockIcon className="h-4 w-4 text-muted-foreground" />
            )}
            <span className="text-sm font-medium">
              {isGenerating ? "Generating problem..." : "Ready to generate"}
            </span>
          </div>
        </div>
      </div>

      {/* Focus Areas Section */}
      <Collapsible
        open={focusAreasOpen}
        onOpenChange={setFocusAreasOpen}
        className="border border-border rounded-lg p-3 bg-secondary"
      >
        <CollapsibleTrigger className="w-full">
          <div className="flex items-center justify-between gap-2 w-full">
            <div className="flex items-center gap-2">
              <ChevronDownIcon
                className={`h-4 w-4 transition-transform ${
                  focusAreasOpen ? "rotate-0" : "-rotate-90"
                }`}
              />
              <h3 className="text-sm font-medium">Focus Areas</h3>
              {selectedFocusAreaIds.length === 0 && (
                <Badge variant="secondary" className="text-xs">
                  Random
                </Badge>
              )}
              {selectedFocusAreaIds.length > 0 && (
                <Badge variant="outline" className="text-xs">
                  {selectedFocusAreaIds.length} selected
                </Badge>
              )}
            </div>
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent className="space-y-3 pt-3">
          <div className="space-y-2">
            <div className="text-xs text-muted-foreground">
              Generate new problem with different focus areas:
            </div>
            <FocusAreaSelector
              focusAreas={focusAreas}
              selectedIds={selectedFocusAreaIds}
              onChange={setSelectedFocusAreaIds}
              disabled={isGenerating}
            />
          </div>
        </CollapsibleContent>
      </Collapsible>

      {/* Generate Button */}
      <Button
        onClick={handleGenerateProblem}
        disabled={isGenerating}
        className="w-full"
      >
        {isGenerating ? (
          <>
            <Loader2Icon className="h-4 w-4 mr-2 animate-spin" />
            Creating Problem...
          </>
        ) : (
          "Generate New Problem"
        )}
      </Button>

      {/* Disabled buttons for empty state */}
      <div className="flex gap-2 w-full">
        <Button variant="outline" size="sm" className="flex-1" disabled>
          Make Easier
        </Button>
        <Button variant="outline" size="sm" className="flex-1" disabled>
          Make Harder
        </Button>
      </div>
    </div>
  );
}
